<?php
/**
 * This file is part of
 * Kimai - Open Source Time Tracking // http://www.kimai.org
 * (c) Kimai-Development-Team - since 2006
 *
 * Kimai is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; Version 3, 29 June 2007
 *
 * Kimai is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Kimai; If not, see <http://www.gnu.org/licenses/>.
 */

// This file was automatically generated by the installer

$server_hostname = "localhost";
$server_database = "kimai";
$server_username = "root";
$server_password = "123456";
$server_prefix   = "kimai_";
$language        = "en";
$password_salt   = "Uj2dViBnJ5HB2ipqwJWkE";
$defaultTimezone = "UTC";
$skin            = "standard";
$authenticator   = "kimai";
$billable        = array (
  0 => 0,
  1 => 50,
  2 => 100,
);
